# Generated by Django 5.2.4 on 2025-07-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('message_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver', models.CharField(max_length=20)),
                ('sender', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Message Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('dnd', 'DND Active'), ('expired', 'Expired'), ('rejected', 'Rejected')], max_length=20)),
                ('channel', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sent_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
